In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


##### Initalizing Different Types of Arrays

In [4]:
#ALl 0s matrix
np.zeros(5)
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.zeros((2,3,3))
#the results
#array([[[0., 0., 0.],
#        [0., 0., 0.],
#       [0., 0., 0.]],

#      [[0., 0., 0.],
#       [0., 0., 0.],
#       [0., 0., 0.]]])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.zeros((2,3,3,2))
#the results
# array([[[[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]]],


#        [[[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]]]])

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [7]:
#All 1s matrix
np.ones((4,2,2), dtype= 'int32')

#the results
# array([[[1, 1],
#         [1, 1]],

#        [[1, 1],
#         [1, 1]],

#        [[1, 1],
#         [1, 1]],

#        [[1, 1],
#         [1, 1]]])

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [8]:
#Any other number
np.full ((2,2), 99)
#the results
# array([[99, 99],
#        [99, 99]])

array([[99, 99],
       [99, 99]])

In [9]:
#Any other number (full_like)
np.full_like(a, 4)
#the results
# array([[4, 4, 4],
#        [4, 4, 4]])

array([[4, 4, 4],
       [4, 4, 4]])

In [10]:
#the same syntax : 
# np.full_like(a, 4) = np.full(a.shape,4)
np.full(a.shape, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [11]:
#Random decimal numbers
np.random.rand(4,2,3)

array([[[0.96457523, 0.20894039, 0.36616619],
        [0.0656118 , 0.31017576, 0.47962253]],

       [[0.19690151, 0.0977927 , 0.26910179],
        [0.5413755 , 0.48266989, 0.45920185]],

       [[0.87566422, 0.17509778, 0.96267775],
        [0.84384601, 0.29148077, 0.81766421]],

       [[0.71454141, 0.73023741, 0.0093706 ],
        [0.3203468 , 0.27399241, 0.92724283]]])

In [12]:
#Random like a shape of 1 matrix
np.random.random_sample(a.shape)

array([[0.98012973, 0.43380361, 0.0833649 ],
       [0.96070236, 0.40058871, 0.96544201]])

In [13]:
#Random Integer values
np.random.randint(7, size =(3,3))

#the result
# array([[1, 4, 4],
#        [4, 4, 6],
#        [6, 1, 0]])

array([[1, 0, 4],
       [2, 3, 1],
       [1, 2, 4]])

In [14]:
np.random.randint(-4,7, size =(3,3))

#the random matrix
# array([[ 1,  2,  2],
#        [ 5,  4, -1],
#        [ 1, -2,  5]])

array([[-4,  0,  6],
       [ 1,  4, -2],
       [-4, -3,  2]])

In [15]:
#The identity matrix(ma tran duong cheo)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [17]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### BE careful when copying arrays!!!

In [18]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(b)
print(a)
#the array b and a same point to 1 value 
#=> the results same
    #[100   2   3]

[100   2   3]
[100   2   3]


In [19]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print (a)
print(b)
# the result is different, and the matrix a is same, just change the first elements of matrix b
# the result:
# [1 2 3]
# [100   2   3]

[1 2 3]
[100   2   3]


##### BASIC MATHEMATICS

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a + 2

array([3, 4, 5, 6])

In [22]:
a-2

array([-1,  0,  1,  2])

In [23]:
a*2

array([2, 4, 6, 8])

In [24]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [25]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [26]:
#lay luy thua
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [27]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [28]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [29]:
#multiple two matrix
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [30]:
#find the determinant(tinh dinh thuc cua ma tran xac dinh)
c = np.identity(3)
np.linalg.det(c)

1.0

##### Stastics

In [32]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# the minimum elements of the stats matrix
np.min(stats)

1

In [34]:
# the maximum elements of the stats matrix
np.max(stats)

6

In [36]:
# axis = 0 => gia tri lon nhat trong cot
np.max(stats, axis = 0)
#the results :
#   np.array([4,5,6])

# axis = 1 => gia tri lon nhat trong hang
np.max(stats, axis = 1)
#the results:
#   array([3,6])

array([3, 6])

In [37]:
np.sum(stats)

21

##### REORGANIZING ARRAYS

In [38]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [40]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

MIScellaneous


##### Load Data from File


In [44]:
# load data from file txt
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 466.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [45]:
#copy a filedata with type int32
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 466,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [46]:
#the original data of file
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 466.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

##### Boolean Masking and Advanced Indexing

In [48]:
filedata > 50
#the result:
# array([[False, False, False, False,  True,  True, False, False, False,
#         False, False, False, False, False, False, False, False, False],
#        [False, False, False, False,  True,  True, False,  True, False,
#         False, False, False, False, False, False, False, False, False],
#        [False, False, False, False,  True, False, False, False,  True,
#         False, False, False, False, False, False, False,  True,  True]])

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [49]:
filedata[filedata > 50]
#the result: array([196.,  75., 466.,  75.,  55., 999.,  78.,  76.,  88.])


array([196.,  75., 466.,  75.,  55., 999.,  78.,  76.,  88.])

In [50]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [51]:
#so sanh cot gia tri voi 50, neu co 1 gia tri >50 thi tra ve True
np.any(filedata >50, axis=0)
#the result:
# array([False, False, False, False,  True,  True, False,  True,  True,
#        False, False, False, False, False, False, False,  True,  True])

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [52]:
#so sanh cot gia tri voi 50, neu tat cagia tri >50 thi tra ve True
np.all(filedata > 50, axis=0)
#the results:
# array([False, False, False, False,  True, False, False, False, False,
#        False, False, False, False, False, False, False, False, False])

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [54]:
((filedata > 50) & (filedata < 100))
#the results:
# array([[False, False, False, False, False,  True, False, False, False,
#         False, False, False, False, False, False, False, False, False],
#        [False, False, False, False, False,  True, False,  True, False,
#         False, False, False, False, False, False, False, False, False],
#        [False, False, False, False, False, False, False, False,  True,
#         False, False, False, False, False, False, False,  True,  True]])

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [55]:
# not (reverse the results of the condition with ~)
(~((filedata > 50) & (filedata < 100)))

#the results:
# array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
#          True,  True,  True,  True,  True,  True,  True,  True,  True],
#        [ True,  True,  True,  True,  True, False,  True, False,  True,
#          True,  True,  True,  True,  True,  True,  True,  True,  True],
#        [ True,  True,  True,  True,  True,  True,  True,  True, False,
#          True,  True,  True,  True,  True,  True,  True, False, False]])

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])